Removed autodownload from the scripts.

diff --git a/src/linux/sbt b/src/linux/sbt
--- a/src/linux/sbt
+++ b/src/linux/sbt
@@ -43,7 +43,7 @@ declare -r sbt_release_version=0.11.3
 unset sbt_rc_version
 # declare -r sbt_rc_version=
 declare -r sbt_snapshot_version=0.11.4-SNAPSHOT
-declare -r sbt_snapshot_baseurl="http://typesafe.artifactoryonline.com/typesafe/ivy-snapshots/org.scala-tools.sbt/sbt-launch/"
+declare -r sbt_snapshot_baseurl="http://typesafe.artifactoryonline.com/typesafe/ivy-snapshots/org.scala-sbt/sbt-launch/"
 
 declare -r default_java_opts="-Dfile.encoding=UTF8"
 declare -r default_sbt_opts="-XX:+CMSClassUnloadingEnabled"
@@ -191,17 +191,12 @@ download_url () {
   local url="$1"
   local jar="$2"
 
-  echo "Downloading sbt launcher $sbt_version:"
+  echo "Cannot find sbt launcher $sbt_version"
+  echo "Please download: "
   echo "  From  $url"
   echo "    To  $jar"
 
-  mkdir -p $(dirname "$jar") && {
-    if which curl >/dev/null; then
-      curl --silent "$url" --output "$jar"
-    elif which wget >/dev/null; then
-      wget --quiet -O "$jar" "$url"
-    fi
-  } && [[ -f "$jar" ]]
+  exit 1
 }
 
 acquire_sbt_jar () {
diff --git a/src/universal/bin/sbt b/src/universal/bin/sbt
--- a/src/universal/bin/sbt
+++ b/src/universal/bin/sbt
@@ -192,17 +192,12 @@ download_url () {
   local url="$1"
   local jar="$2"
 
-  echo "Downloading sbt launcher $sbt_version:"
+  echo "Cannot find sbt launcher $sbt_version"
+  echo "Please download: "
   echo "  From  $url"
   echo "    To  $jar"
 
-  mkdir -p $(dirname "$jar") && {
-    if which curl >/dev/null; then
-      curl --silent "$url" --output "$jar"
-    elif which wget >/dev/null; then
-      wget --quiet -O "$jar" "$url"
-    fi
-  } && [[ -f "$jar" ]]
+  exit 1
 }
 
 acquire_sbt_jar () {
